_wandb:
    value:
        cli_version: 0.23.1
        e:
            fdhcztwl2tleuzkuuonvvr8s0lm330ds:
                args:
                    - --lr
                    - "2e-7"
                    - --start_epoch
                    - "1000"
                    - --epochs
                    - "1100"
                    - --batch_size
                    - "8"
                    - --accum_iter
                    - "4"
                codePath: FSC_train.py
                codePathLocal: FSC_train.py
                cpu_count: 10
                cpu_count_logical: 16
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "997814431744"
                        used: "764300722176"
                email: nguyenlam.baophuc@gmail.com
                executable: C:\Users\ADMIN\anaconda3\python.exe
                git:
                    commit: c32a36858df60145ad372693fbd336faf255dba2
                    remote: https://github.com/BPhucKHMT/VA_Count.git
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 3072
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-655a4ae2-739e-9e6e-3580-6b89eb75a255
                host: LAPTOP-U9ETFAIE
                memory:
                    total: "25480454144"
                os: Windows-11-10.0.26100-SP0
                program: C:\uit_HK5\Cs331\VA-Count\FSC_train.py
                python: CPython 3.12.7
                root: C:\uit_HK5\Cs331\VA-Count
                startedAt: "2026-01-17T07:32:35.576346Z"
                writerId: fdhcztwl2tleuzkuuonvvr8s0lm330ds
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 41
                - 49
                - 63
                - 105
            "2":
                - 1
                - 41
                - 49
                - 63
                - 105
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.12.7
            "5": 0.23.1
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
accum_iter:
    value: 4
anno_file:
    value: data\FSC147\annotation_FSC147_pos_final.json
anno_file_negative:
    value: ./data/FSC147/annotation_FSC147_neg_final.json
batch_size:
    value: 8
blr:
    value: 0.001
class_file:
    value: data\FSC147\ImageClasses_FSC147.txt
data_path:
    value: ./data/FSC147/
data_split_file:
    value: data\FSC147\Train_Test_Val_FSC_147.json
device:
    value: cuda
dist_on_itp:
    value: false
dist_url:
    value: env://
distributed:
    value: false
do_aug:
    value: true
do_resume:
    value: false
epochs:
    value: 1100
im_dir:
    value: data\FSC147\images_384_VarV2
local_rank:
    value: -1
lr:
    value: 2e-07
mask_ratio:
    value: 0.5
min_lr:
    value: 0
model:
    value: mae_vit_base_patch16
norm_pix_loss:
    value: false
num_workers:
    value: 10
output_dir:
    value: ./data/out/fim6_dir
pin_mem:
    value: true
resume:
    value: ./data/checkpoint_FSC_dino_prompt_final.pth
seed:
    value: 0
start_epoch:
    value: 1000
team:
    value: wsense
title:
    value: count
wandb:
    value: "240227"
wandb_id:
    value: null
warmup_epochs:
    value: 10
weight_decay:
    value: 0.05
world_size:
    value: 1
